import { pgTable, serial, bigint, text, boolean } from 'drizzle-orm/pg-core';

export const companies = pgTable('companies', {
  id: serial('id').primaryKey(),
  nombre: text('nombre'),
  ruc: text('ruc').notNull(),
  razonSocial: text('razon_social').notNull(),
  nombreComercial: text('nombre_comercial'),
  direccion: text('direccion'),
  ubigeo: text('ubigeo'),
  distrito: text('distrito'),
  provincia: text('provincia'),
  departamento: text('departamento'),
  telefono: text('telefono'),
  email: text('email'),
  usuarioSol: text('usuario_sol'),
  claveSol: text('clave_sol'),
  certificado: text('certificado'),
  certificadoPassword: text('certificado_password'),
  sellerUsername: text('seller_username'),
  sellerPassword: text('seller_password'),
  falabellaApiUserId: text('falabella_api_user_id'),
  falabellaApiKey: text('falabella_api_key'),
  ripleyApiKey: text('ripley_api_key'),
  ripleyShopId: text('ripley_shop_id'),
  logoPath: text('logo_path'),
  activo: boolean('activo').default(true),
  createdAt: bigint('created_at', { mode: 'number' }),
  updatedAt: bigint('updated_at', { mode: 'number' }),
});
